"""Composite logger for NeuroLens — writes to W&B + PostgreSQL + JSONL.

Design principles (see docs/private/blueprint/01-architecture.md):

1. Dual-write architecture: every event is written to three independent
   destinations. If one fails, the others remain intact (audit trail).

2. Graceful fallback: the logger must NEVER break the training loop.
   If W&B is unreachable, training continues with Postgres + JSONL only.
   If Postgres is unreachable, training continues with W&B + JSONL.
   If JSONL fails (filesystem), we still try the remote destinations.

3. The Postgres run_id is the canonical identifier — it is included in
   every JSONL event and used to correlate logs across all three sinks.

4. JSONL is append-only with one JSON document per line, fsync after each
   write so an aborted kernel still leaves a trail on disk.
"""

from __future__ import annotations

import contextlib
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import wandb

from neurolens.db.repository import finish_run, insert_run, log_metric


def _iso_now() -> str:
    """Return current UTC time as ISO-8601 string with Z suffix."""
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


class CompositeLogger:
    """Writes runs and metrics to W&B + PostgreSQL + JSONL simultaneously.

    Typical usage inside a training kernel::

        logger = CompositeLogger(
            project="neurolens",
            experiment="vgg16-fold0",
            config={"arch": "vgg16", "stage": 1, "lr": 1e-3, ...},
            jsonl_dir=Path("/kaggle/working/jsonl"),
        )
        for epoch in range(epochs):
            train_metrics = train_one_epoch(...)
            logger.log(epoch=epoch, phase="train", metrics=train_metrics)
            val_metrics = evaluate(...)
            logger.log(epoch=epoch, phase="val", metrics=val_metrics)
        logger.finish(status="completed", final_metrics=test_metrics)
    """

    def __init__(
        self,
        project: str,
        experiment: str,
        config: dict[str, Any],
        jsonl_dir: Path,
        *,
        wandb_group: str | None = None,
        wandb_name: str | None = None,
        wandb_tags: list[str] | None = None,
        git_commit: str | None = None,
        kaggle_kernel_url: str | None = None,
    ) -> None:
        """Initialize the composite logger.

        Args:
            project: W&B project name (e.g., "neurolens").
            experiment: experiment name in Postgres (groups related runs).
            config: hyperparameter dict; must contain at least 'arch' and 'stage'.
            jsonl_dir: directory where JSONL log will be written.
            wandb_group: W&B group; defaults to ``experiment``.
            wandb_name: W&B run name; defaults to auto-generated by W&B.
            wandb_tags: W&B tags for filtering.
            git_commit: SHA of the commit being run (reproducibility).
            kaggle_kernel_url: URL of the Kaggle kernel (cross-reference).

        The logger MUST receive at least 'arch' and 'stage' in config.
        """
        if "arch" not in config:
            raise ValueError("config must contain 'arch'")
        if "stage" not in config:
            raise ValueError("config must contain 'stage'")

        self.project = project
        self.experiment = experiment
        self.config = config
        self._wandb_run: Any = None
        self._postgres_run_id: int | None = None
        self._jsonl_fp: Any = None
        self._jsonl_path: Path | None = None

        # --- W&B initialization (best effort) ---------------------------------
        try:
            self._wandb_run = wandb.init(
                project=project,
                group=wandb_group or experiment,
                name=wandb_name,
                config=config,
                tags=wandb_tags,
                reinit=True,
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[CompositeLogger] WARNING: W&B init failed ({exc!r}); continuing without W&B")
            self._wandb_run = None

        # --- PostgreSQL run insertion (best effort) ---------------------------
        try:
            self._postgres_run_id = insert_run(
                experiment_name=experiment,
                arch=str(config["arch"]),
                stage=int(config["stage"]),
                hyperparams=config,
                fold=config.get("fold"),
                wandb_run_id=self._wandb_run.id if self._wandb_run else None,
                wandb_url=self._wandb_run.url if self._wandb_run else None,
                git_commit=git_commit,
                kaggle_kernel_url=kaggle_kernel_url,
            )
        except Exception as exc:  # noqa: BLE001
            print(
                f"[CompositeLogger] WARNING: Postgres insert_run failed ({exc!r}); "
                "continuing without Postgres"
            )
            self._postgres_run_id = None

        # --- JSONL initialization ---------------------------------------------
        try:
            jsonl_dir.mkdir(parents=True, exist_ok=True)
            run_label = (
                str(self._postgres_run_id)
                if self._postgres_run_id is not None
                else (self._wandb_run.id if self._wandb_run else f"local-{_iso_now()}")
            )
            self._jsonl_path = jsonl_dir / f"{run_label}.jsonl"
            self._jsonl_fp = self._jsonl_path.open("a", encoding="utf-8")
        except Exception as exc:  # noqa: BLE001
            print(
                f"[CompositeLogger] WARNING: JSONL init failed ({exc!r}); continuing without JSONL"
            )
            self._jsonl_fp = None
            self._jsonl_path = None

        # --- Emit run_start event ---------------------------------------------
        self._write_jsonl(
            {
                "event": "run_start",
                "experiment": experiment,
                "config": config,
                "wandb_run_id": self._wandb_run.id if self._wandb_run else None,
                "postgres_run_id": self._postgres_run_id,
            }
        )

    # ------------------------------------------------------------------ public

    @property
    def run_id(self) -> int | None:
        """Postgres run id (None if Postgres was unavailable at init)."""
        return self._postgres_run_id

    @property
    def wandb_run(self) -> Any:
        """The wandb Run object (None if W&B was unavailable at init)."""
        return self._wandb_run

    @property
    def jsonl_path(self) -> Path | None:
        """Path to the JSONL log file (None if filesystem failed at init)."""
        return self._jsonl_path

    def log(self, *, epoch: int, phase: str, metrics: dict[str, float]) -> None:
        """Write a batch of metrics to all three sinks.

        Args:
            epoch: epoch index (0-based).
            phase: one of 'train', 'val', 'test'.
            metrics: dict of metric_name -> float (e.g., {"loss": 0.4, "acc": 0.85}).
        """
        # --- W&B (best effort) ------------------------------------------------
        if self._wandb_run is not None:
            try:
                wandb_payload: dict[str, Any] = {f"{phase}/{k}": v for k, v in metrics.items()}
                wandb_payload["epoch"] = epoch
                self._wandb_run.log(wandb_payload)
            except Exception as exc:  # noqa: BLE001
                print(f"[CompositeLogger] WARNING: wandb.log failed ({exc!r})")

        # --- PostgreSQL (best effort) -----------------------------------------
        if self._postgres_run_id is not None:
            for name, value in metrics.items():
                try:
                    log_metric(
                        run_id=self._postgres_run_id,
                        epoch=epoch,
                        phase=phase,
                        name=name,
                        value=float(value),
                    )
                except Exception as exc:  # noqa: BLE001
                    print(
                        f"[CompositeLogger] WARNING: log_metric failed for {phase}/{name} ({exc!r})"
                    )

        # --- JSONL (best effort) ----------------------------------------------
        self._write_jsonl(
            {
                "event": "epoch_end",
                "epoch": epoch,
                "phase": phase,
                **metrics,
            }
        )

    def finish(
        self,
        status: str = "completed",
        final_metrics: dict[str, Any] | None = None,
        error_message: str | None = None,
    ) -> None:
        """Close the logger, flushing run summary to all sinks.

        Args:
            status: 'completed', 'failed', or 'cancelled'.
            final_metrics: final summary metrics (test_acc, f1_macro, etc.).
            error_message: required if status='failed'; ignored otherwise.
        """
        # --- PostgreSQL (best effort) -----------------------------------------
        if self._postgres_run_id is not None:
            try:
                finish_run(
                    run_id=self._postgres_run_id,
                    status=status,
                    final_metrics=final_metrics,
                    error_message=error_message,
                )
            except Exception as exc:  # noqa: BLE001
                print(f"[CompositeLogger] WARNING: finish_run failed ({exc!r})")

        # --- JSONL run_complete event -----------------------------------------
        self._write_jsonl(
            {
                "event": "run_complete",
                "status": status,
                "final_metrics": final_metrics,
                "error_message": error_message,
            }
        )

        # --- W&B summary + finish ---------------------------------------------
        if self._wandb_run is not None:
            try:
                if final_metrics:
                    for k, v in final_metrics.items():
                        if isinstance(v, (int, float)):
                            self._wandb_run.summary[k] = v
                wandb.finish(exit_code=0 if status == "completed" else 1)
            except Exception as exc:  # noqa: BLE001
                print(f"[CompositeLogger] WARNING: wandb.finish failed ({exc!r})")

        # --- Close JSONL file pointer -----------------------------------------
        if self._jsonl_fp is not None:
            with contextlib.suppress(Exception):
                self._jsonl_fp.close()
            self._jsonl_fp = None

    # ----------------------------------------------------------------- private

    def _write_jsonl(self, payload: dict[str, Any]) -> None:
        """Append one JSON document to the JSONL log, with fsync.

        Silently no-ops if JSONL init failed (logger still works on other sinks).
        """
        if self._jsonl_fp is None:
            return
        try:
            enriched = {"timestamp": _iso_now(), **payload}
            self._jsonl_fp.write(json.dumps(enriched, default=str) + "\n")
            self._jsonl_fp.flush()
        except Exception as exc:  # noqa: BLE001
            print(f"[CompositeLogger] WARNING: JSONL write failed ({exc!r})")
